{{- if .Values.rbac.create -}}
{{- $fullname := include "cnpg-operations.fullname" . -}}
{{- $labels := include "cnpg-operations.labels" . -}}
{{- $saName := include "cnpg-operations.serviceAccountName" . -}}
{{- range $cr := .Values.rbac.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}-{{ $cr | replace "." "-" }}
  labels:
    {{- $labels | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $cr }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}-secrets
  labels:
    {{- $labels | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}-secrets
  labels:
    {{- $labels | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }}-secrets
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
