// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "CNPG Operations"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cluster": {
            "get": {
                "description": "List all CloudNativePG clusters in the given namespace (defaults to server namespace)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "List PostgreSQL clusters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ClustersListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new CloudNativePG PostgreSQL cluster with HA configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Create a PostgreSQL cluster",
                "parameters": [
                    {
                        "description": "Cluster configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.CreateClusterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "dry_run=true",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.DryRunResponse"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ClusterCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cluster/{name}": {
            "get": {
                "description": "Get detailed status for a specific CloudNativePG cluster",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Get a PostgreSQL cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ClusterResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently delete a CloudNativePG cluster and its associated role secrets. Requires confirm=true.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Delete a PostgreSQL cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Must be true to confirm destructive deletion",
                        "name": "confirm",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Preview deletion without executing",
                        "name": "dry_run",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cluster/{name}/database": {
            "get": {
                "description": "List all Database CRDs managed for a CloudNativePG cluster",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "List PostgreSQL databases",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.DatabasesListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Database CRD that CloudNativePG will reconcile into a PostgreSQL database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Create a PostgreSQL database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "description": "Database configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.CreateDatabaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "dry_run=true",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.DryRunResponse"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.DatabaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cluster/{name}/database/{database}": {
            "delete": {
                "description": "Delete the Database CRD for a cluster. Whether the actual database is dropped depends on its reclaimPolicy.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Delete a PostgreSQL database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Database name",
                        "name": "database",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Preview deletion without executing",
                        "name": "dry_run",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cluster/{name}/role": {
            "get": {
                "description": "List all roles managed in a CloudNativePG cluster via spec.managed.roles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "List PostgreSQL roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.RolesListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new role in a CloudNativePG cluster. Auto-generates a password stored in a Kubernetes secret.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Create a PostgreSQL role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "description": "Role configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.CreateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "dry_run=true",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.DryRunResponse"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.RoleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cluster/{name}/role/{role}": {
            "put": {
                "description": "Update attributes and/or password of an existing role in a CloudNativePG cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Update a PostgreSQL role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Role name",
                        "name": "role",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "description": "Role update (all fields optional)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.UpdateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.RoleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a role from a CloudNativePG cluster and delete its associated Kubernetes secret",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "Delete a PostgreSQL role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Role name",
                        "name": "role",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Preview deletion without executing",
                        "name": "dry_run",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cluster/{name}/scale": {
            "patch": {
                "description": "Change the number of instances in a CloudNativePG cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Scale a PostgreSQL cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kubernetes namespace (defaults to server namespace)",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "description": "Scale configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ScaleClusterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.ClusterCreateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "cluster created"
                },
                "name": {
                    "type": "string",
                    "example": "my-cluster"
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.ClusterInfo": {
            "type": "object",
            "properties": {
                "conditions": {
                    "type": "array",
                    "items": {}
                },
                "current_primary": {
                    "type": "string",
                    "example": "my-cluster-1"
                },
                "instances": {
                    "type": "integer",
                    "example": 3
                },
                "name": {
                    "type": "string",
                    "example": "my-cluster"
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                },
                "phase": {
                    "type": "string",
                    "example": "Cluster in healthy state"
                },
                "postgres_version": {
                    "type": "string",
                    "example": "ghcr.io/cloudnative-pg/postgresql:16"
                },
                "postgresql_parameters": {},
                "ready_instances": {
                    "type": "integer",
                    "example": 3
                },
                "storage_class": {
                    "type": "string",
                    "example": "standard"
                },
                "storage_size": {
                    "type": "string",
                    "example": "10Gi"
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.ClusterResponse": {
            "type": "object",
            "properties": {
                "cluster": {
                    "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ClusterInfo"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.ClustersListResponse": {
            "type": "object",
            "properties": {
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.ClusterInfo"
                    }
                },
                "count": {
                    "type": "integer",
                    "example": 2
                },
                "scope": {
                    "type": "string",
                    "example": "all namespaces"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.CreateClusterRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "dry_run": {
                    "type": "boolean",
                    "example": false
                },
                "instances": {
                    "type": "integer",
                    "example": 3
                },
                "name": {
                    "type": "string",
                    "example": "my-cluster"
                },
                "namespace": {
                    "type": "string",
                    "example": ""
                },
                "postgres_version": {
                    "type": "string",
                    "example": "16"
                },
                "storage_class": {
                    "type": "string",
                    "example": ""
                },
                "storage_size": {
                    "type": "string",
                    "example": "10Gi"
                },
                "timeout": {
                    "type": "integer",
                    "example": 180
                },
                "wait": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.CreateDatabaseRequest": {
            "type": "object",
            "required": [
                "database_name",
                "owner"
            ],
            "properties": {
                "database_name": {
                    "type": "string",
                    "example": "my-db"
                },
                "dry_run": {
                    "type": "boolean",
                    "example": false
                },
                "owner": {
                    "type": "string",
                    "example": "myuser"
                },
                "reclaim_policy": {
                    "type": "string",
                    "example": "retain"
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.CreateRoleRequest": {
            "type": "object",
            "required": [
                "role_name"
            ],
            "properties": {
                "createdb": {
                    "type": "boolean",
                    "example": false
                },
                "createrole": {
                    "type": "boolean",
                    "example": false
                },
                "dry_run": {
                    "type": "boolean",
                    "example": false
                },
                "inherit": {
                    "type": "boolean",
                    "example": true
                },
                "login": {
                    "type": "boolean",
                    "example": true
                },
                "replication": {
                    "type": "boolean",
                    "example": false
                },
                "role_name": {
                    "type": "string",
                    "example": "myuser"
                },
                "superuser": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.DatabaseInfo": {
            "type": "object",
            "properties": {
                "crd_name": {
                    "type": "string",
                    "example": "my-cluster-my-db"
                },
                "database_name": {
                    "type": "string",
                    "example": "my-db"
                },
                "ensure": {
                    "type": "string",
                    "example": "present"
                },
                "owner": {
                    "type": "string",
                    "example": "myuser"
                },
                "reclaim_policy": {
                    "type": "string",
                    "example": "retain"
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.DatabaseResponse": {
            "type": "object",
            "properties": {
                "database": {
                    "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.DatabaseInfo"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.DatabasesListResponse": {
            "type": "object",
            "properties": {
                "cluster": {
                    "type": "string",
                    "example": "default/my-cluster"
                },
                "count": {
                    "type": "integer",
                    "example": 1
                },
                "databases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.DatabaseInfo"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.DryRunResponse": {
            "type": "object",
            "properties": {
                "dry_run": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "dry run completed"
                },
                "preview": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 404
                },
                "error": {
                    "type": "string",
                    "example": "cluster not found"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "operation completed successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.RoleInfo": {
            "type": "object",
            "properties": {
                "createdb": {
                    "type": "boolean",
                    "example": false
                },
                "createrole": {
                    "type": "boolean",
                    "example": false
                },
                "ensure": {
                    "type": "string",
                    "example": "present"
                },
                "in_roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "inherit": {
                    "type": "boolean",
                    "example": true
                },
                "login": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "myuser"
                },
                "password_secret": {
                    "type": "string",
                    "example": "cnpg-my-cluster-user-myuser"
                },
                "replication": {
                    "type": "boolean",
                    "example": false
                },
                "superuser": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.RoleResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.RoleInfo"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.RolesListResponse": {
            "type": "object",
            "properties": {
                "cluster": {
                    "type": "string",
                    "example": "default/my-cluster"
                },
                "count": {
                    "type": "integer",
                    "example": 1
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cnpg-operations_cnpg-rest-server_internal_models.RoleInfo"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.ScaleClusterRequest": {
            "type": "object",
            "required": [
                "instances"
            ],
            "properties": {
                "dry_run": {
                    "type": "boolean",
                    "example": false
                },
                "instances": {
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 1,
                    "example": 5
                }
            }
        },
        "github_com_cnpg-operations_cnpg-rest-server_internal_models.UpdateRoleRequest": {
            "type": "object",
            "properties": {
                "createdb": {
                    "type": "boolean",
                    "example": false
                },
                "createrole": {
                    "type": "boolean",
                    "example": false
                },
                "dry_run": {
                    "type": "boolean",
                    "example": false
                },
                "inherit": {
                    "type": "boolean",
                    "example": true
                },
                "login": {
                    "type": "boolean",
                    "example": true
                },
                "password": {
                    "type": "string",
                    "example": "newpassword123"
                },
                "replication": {
                    "type": "boolean",
                    "example": false
                },
                "superuser": {
                    "type": "boolean",
                    "example": false
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "CNPG REST API",
	Description:      "REST API for managing CloudNativePG PostgreSQL clusters on Kubernetes.\nProvides full cluster lifecycle management, role/user management, and database management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
