// Code generated by swaggo/swag. DO NOT EDIT.
// Run `make swagger` to regenerate this file from handler annotations.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "REST API for managing CloudNativePG PostgreSQL clusters on Kubernetes.",
        "title": "CNPG REST API",
        "contact": {},
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "CNPG REST API",
	Description:      "REST API for managing CloudNativePG PostgreSQL clusters on Kubernetes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
